package dev.rapid.domain;
// Generated Jan 24, 2016 10:48:55 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BatDongSan generated by hbm2java
 */
@Entity
@Table(name = "bat_dong_san", catalog = "thamdinhgia_db")
public class BatDongSan implements java.io.Serializable {

	private Integer idDbs;
	private String viTri;
	private Double dienTich;
	private String hinhDang;
	private String kichThuoc;
	private String matTien;
	private String loaiDat;
	private Date thoiHanSd;
	private String mucDichSd;
	private String nguonGoc;
	private Double giaUbnd;
	private String haTang;
	private Set<TaiSan> taiSans = new HashSet<TaiSan>(0);

	public BatDongSan() {
	}

	public BatDongSan(String viTri, Double dienTich, String hinhDang, String kichThuoc, String matTien, String loaiDat,
			Date thoiHanSd, String mucDichSd, String nguonGoc, Double giaUbnd, String haTang, Set<TaiSan> taiSans) {
		this.viTri = viTri;
		this.dienTich = dienTich;
		this.hinhDang = hinhDang;
		this.kichThuoc = kichThuoc;
		this.matTien = matTien;
		this.loaiDat = loaiDat;
		this.thoiHanSd = thoiHanSd;
		this.mucDichSd = mucDichSd;
		this.nguonGoc = nguonGoc;
		this.giaUbnd = giaUbnd;
		this.haTang = haTang;
		this.taiSans = taiSans;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID_DBS", unique = true, nullable = false)
	public Integer getIdDbs() {
		return this.idDbs;
	}

	public void setIdDbs(Integer idDbs) {
		this.idDbs = idDbs;
	}

	@Column(name = "VI_TRI", length = 100)
	public String getViTri() {
		return this.viTri;
	}

	public void setViTri(String viTri) {
		this.viTri = viTri;
	}

	@Column(name = "DIEN_TICH", precision = 22, scale = 0)
	public Double getDienTich() {
		return this.dienTich;
	}

	public void setDienTich(Double dienTich) {
		this.dienTich = dienTich;
	}

	@Column(name = "HINH_DANG", length = 100)
	public String getHinhDang() {
		return this.hinhDang;
	}

	public void setHinhDang(String hinhDang) {
		this.hinhDang = hinhDang;
	}

	@Column(name = "KICH_THUOC", length = 100)
	public String getKichThuoc() {
		return this.kichThuoc;
	}

	public void setKichThuoc(String kichThuoc) {
		this.kichThuoc = kichThuoc;
	}

	@Column(name = "MAT_TIEN", length = 100)
	public String getMatTien() {
		return this.matTien;
	}

	public void setMatTien(String matTien) {
		this.matTien = matTien;
	}

	@Column(name = "LOAI_DAT", length = 100)
	public String getLoaiDat() {
		return this.loaiDat;
	}

	public void setLoaiDat(String loaiDat) {
		this.loaiDat = loaiDat;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "THOI_HAN_SD", length = 19)
	public Date getThoiHanSd() {
		return this.thoiHanSd;
	}

	public void setThoiHanSd(Date thoiHanSd) {
		this.thoiHanSd = thoiHanSd;
	}

	@Column(name = "MUC_DICH_SD", length = 100)
	public String getMucDichSd() {
		return this.mucDichSd;
	}

	public void setMucDichSd(String mucDichSd) {
		this.mucDichSd = mucDichSd;
	}

	@Column(name = "NGUON_GOC", length = 100)
	public String getNguonGoc() {
		return this.nguonGoc;
	}

	public void setNguonGoc(String nguonGoc) {
		this.nguonGoc = nguonGoc;
	}

	@Column(name = "GIA_UBND", precision = 22, scale = 0)
	public Double getGiaUbnd() {
		return this.giaUbnd;
	}

	public void setGiaUbnd(Double giaUbnd) {
		this.giaUbnd = giaUbnd;
	}

	@Column(name = "HA_TANG", length = 100)
	public String getHaTang() {
		return this.haTang;
	}

	public void setHaTang(String haTang) {
		this.haTang = haTang;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "batDongSan")
	public Set<TaiSan> getTaiSans() {
		return this.taiSans;
	}

	public void setTaiSans(Set<TaiSan> taiSans) {
		this.taiSans = taiSans;
	}

}
