package dev.rapid.domain;
// Generated Jan 24, 2016 10:48:55 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * GiaTriDoanhNghiep generated by hbm2java
 */
@Entity
@Table(name = "gia_tri_doanh_nghiep", catalog = "thamdinhgia_db")
public class GiaTriDoanhNghiep implements java.io.Serializable {

	private Integer idDn;
	private String linhVucKd;
	private Double vonChuSoHuu;
	private Double tongTaiSan;
	private Float tySuatLoiNhuan;
	private Set<TaiSan> taiSans = new HashSet<TaiSan>(0);

	public GiaTriDoanhNghiep() {
	}

	public GiaTriDoanhNghiep(String linhVucKd, Double vonChuSoHuu, Double tongTaiSan, Float tySuatLoiNhuan,
			Set<TaiSan> taiSans) {
		this.linhVucKd = linhVucKd;
		this.vonChuSoHuu = vonChuSoHuu;
		this.tongTaiSan = tongTaiSan;
		this.tySuatLoiNhuan = tySuatLoiNhuan;
		this.taiSans = taiSans;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_DN", unique = true, nullable = false)
	public Integer getIdDn() {
		return this.idDn;
	}

	public void setIdDn(Integer idDn) {
		this.idDn = idDn;
	}

	@Column(name = "LINH_VUC_KD", length = 100)
	public String getLinhVucKd() {
		return this.linhVucKd;
	}

	public void setLinhVucKd(String linhVucKd) {
		this.linhVucKd = linhVucKd;
	}

	@Column(name = "VON_CHU_SO_HUU", precision = 22, scale = 0)
	public Double getVonChuSoHuu() {
		return this.vonChuSoHuu;
	}

	public void setVonChuSoHuu(Double vonChuSoHuu) {
		this.vonChuSoHuu = vonChuSoHuu;
	}

	@Column(name = "TONG_TAI_SAN", precision = 22, scale = 0)
	public Double getTongTaiSan() {
		return this.tongTaiSan;
	}

	public void setTongTaiSan(Double tongTaiSan) {
		this.tongTaiSan = tongTaiSan;
	}

	@Column(name = "TY_SUAT_LOI_NHUAN", precision = 12, scale = 0)
	public Float getTySuatLoiNhuan() {
		return this.tySuatLoiNhuan;
	}

	public void setTySuatLoiNhuan(Float tySuatLoiNhuan) {
		this.tySuatLoiNhuan = tySuatLoiNhuan;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "giaTriDoanhNghiep")
	public Set<TaiSan> getTaiSans() {
		return this.taiSans;
	}

	public void setTaiSans(Set<TaiSan> taiSans) {
		this.taiSans = taiSans;
	}

}
