package dev.rapid.domain;
// Generated Jan 24, 2016 10:48:55 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NhanSu generated by hbm2java
 */
@Entity
@Table(name = "nhan_su", catalog = "thamdinhgia_db")
public class NhanSu implements java.io.Serializable {

	private Integer idNs;
	private String hoTen;
	private String chucVu;
	private String trinhDo;
	private String soCmt;
	private String sdt;
	private Date ngaySinh;
	private String queQuan;
	private Date ngayGiaVao;
	private boolean active;
	private Set<HopDong> hopDongs = new HashSet<HopDong>(0);

	public NhanSu() {
	}

	public NhanSu(String hoTen, boolean active) {
		this.hoTen = hoTen;
		this.active = active;
	}

	public NhanSu(String hoTen, String chucVu, String trinhDo, String soCmt, String sdt, Date ngaySinh, String queQuan,
			Date ngayGiaVao, boolean active, Set<HopDong> hopDongs) {
		this.hoTen = hoTen;
		this.chucVu = chucVu;
		this.trinhDo = trinhDo;
		this.soCmt = soCmt;
		this.sdt = sdt;
		this.ngaySinh = ngaySinh;
		this.queQuan = queQuan;
		this.ngayGiaVao = ngayGiaVao;
		this.active = active;
		this.hopDongs = hopDongs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_NS", unique = true, nullable = false)
	public Integer getIdNs() {
		return this.idNs;
	}

	public void setIdNs(Integer idNs) {
		this.idNs = idNs;
	}

	@Column(name = "HO_TEN", nullable = false, length = 100)
	public String getHoTen() {
		return this.hoTen;
	}

	public void setHoTen(String hoTen) {
		this.hoTen = hoTen;
	}

	@Column(name = "CHUC_VU", length = 100)
	public String getChucVu() {
		return this.chucVu;
	}

	public void setChucVu(String chucVu) {
		this.chucVu = chucVu;
	}

	@Column(name = "TRINH_DO", length = 100)
	public String getTrinhDo() {
		return this.trinhDo;
	}

	public void setTrinhDo(String trinhDo) {
		this.trinhDo = trinhDo;
	}

	@Column(name = "SO_CMT", length = 20)
	public String getSoCmt() {
		return this.soCmt;
	}

	public void setSoCmt(String soCmt) {
		this.soCmt = soCmt;
	}

	@Column(name = "SDT", length = 20)
	public String getSdt() {
		return this.sdt;
	}

	public void setSdt(String sdt) {
		this.sdt = sdt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NGAY_SINH", length = 19)
	public Date getNgaySinh() {
		return this.ngaySinh;
	}

	public void setNgaySinh(Date ngaySinh) {
		this.ngaySinh = ngaySinh;
	}

	@Column(name = "QUE_QUAN", length = 100)
	public String getQueQuan() {
		return this.queQuan;
	}

	public void setQueQuan(String queQuan) {
		this.queQuan = queQuan;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NGAY_GIA_VAO", length = 19)
	public Date getNgayGiaVao() {
		return this.ngayGiaVao;
	}

	public void setNgayGiaVao(Date ngayGiaVao) {
		this.ngayGiaVao = ngayGiaVao;
	}

	@Column(name = "ACTIVE", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhanSu")
	public Set<HopDong> getHopDongs() {
		return this.hopDongs;
	}

	public void setHopDongs(Set<HopDong> hopDongs) {
		this.hopDongs = hopDongs;
	}

}
