package dev.rapid.domain;
// Generated Jan 24, 2016 10:48:55 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PhuongPhap generated by hbm2java
 */
@Entity
@Table(name = "phuong_phap", catalog = "thamdinhgia_db")
public class PhuongPhap implements java.io.Serializable {

	private Integer idPp;
	private String tenPp;
	private Set<TaiSan> taiSans = new HashSet<TaiSan>(0);

	public PhuongPhap() {
	}

	public PhuongPhap(String tenPp) {
		this.tenPp = tenPp;
	}

	public PhuongPhap(String tenPp, Set<TaiSan> taiSans) {
		this.tenPp = tenPp;
		this.taiSans = taiSans;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_PP", unique = true, nullable = false)
	public Integer getIdPp() {
		return this.idPp;
	}

	public void setIdPp(Integer idPp) {
		this.idPp = idPp;
	}

	@Column(name = "TEN_PP", nullable = false, length = 100)
	public String getTenPp() {
		return this.tenPp;
	}

	public void setTenPp(String tenPp) {
		this.tenPp = tenPp;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phuongPhap")
	public Set<TaiSan> getTaiSans() {
		return this.taiSans;
	}

	public void setTaiSans(Set<TaiSan> taiSans) {
		this.taiSans = taiSans;
	}

}
