package dev.rapid.domain;
// Generated Jan 24, 2016 10:48:55 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChiTietHopDongId generated by hbm2java
 */
@Embeddable
public class ChiTietHopDongId implements java.io.Serializable {

	private int idTs;
	private int idHd;

	public ChiTietHopDongId() {
	}

	public ChiTietHopDongId(int idTs, int idHd) {
		this.idTs = idTs;
		this.idHd = idHd;
	}

	@Column(name = "ID_TS", nullable = false)
	public int getIdTs() {
		return this.idTs;
	}

	public void setIdTs(int idTs) {
		this.idTs = idTs;
	}

	@Column(name = "ID_HD", nullable = false)
	public int getIdHd() {
		return this.idHd;
	}

	public void setIdHd(int idHd) {
		this.idHd = idHd;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChiTietHopDongId))
			return false;
		ChiTietHopDongId castOther = (ChiTietHopDongId) other;

		return (this.getIdTs() == castOther.getIdTs()) && (this.getIdHd() == castOther.getIdHd());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdTs();
		result = 37 * result + this.getIdHd();
		return result;
	}

}
