package dev.rapid.domain;
// Generated Jan 24, 2016 10:48:55 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HopDong generated by hbm2java
 */
@Entity
@Table(name = "hop_dong", catalog = "thamdinhgia_db")
public class HopDong implements java.io.Serializable {

	private Integer idHd;
	private KhachHang khachHang;
	private NhanSu nhanSu;
	private String soHd;
	private Date ngayKy;
	private double giaTriHd;
	private Set<ChiTietHopDong> chiTietHopDongs = new HashSet<ChiTietHopDong>(0);

	public HopDong() {
	}

	public HopDong(KhachHang khachHang, NhanSu nhanSu, Date ngayKy, double giaTriHd) {
		this.khachHang = khachHang;
		this.nhanSu = nhanSu;
		this.ngayKy = ngayKy;
		this.giaTriHd = giaTriHd;
	}

	public HopDong(KhachHang khachHang, NhanSu nhanSu, String soHd, Date ngayKy, double giaTriHd,
			Set<ChiTietHopDong> chiTietHopDongs) {
		this.khachHang = khachHang;
		this.nhanSu = nhanSu;
		this.soHd = soHd;
		this.ngayKy = ngayKy;
		this.giaTriHd = giaTriHd;
		this.chiTietHopDongs = chiTietHopDongs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID_HD", unique = true, nullable = false)
	public Integer getIdHd() {
		return this.idHd;
	}

	public void setIdHd(Integer idHd) {
		this.idHd = idHd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_KH", nullable = false)
	public KhachHang getKhachHang() {
		return this.khachHang;
	}

	public void setKhachHang(KhachHang khachHang) {
		this.khachHang = khachHang;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_NS", nullable = false)
	public NhanSu getNhanSu() {
		return this.nhanSu;
	}

	public void setNhanSu(NhanSu nhanSu) {
		this.nhanSu = nhanSu;
	}

	@Column(name = "SO_HD", length = 45)
	public String getSoHd() {
		return this.soHd;
	}

	public void setSoHd(String soHd) {
		this.soHd = soHd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NGAY_KY", nullable = false, length = 19)
	public Date getNgayKy() {
		return this.ngayKy;
	}

	public void setNgayKy(Date ngayKy) {
		this.ngayKy = ngayKy;
	}

	@Column(name = "GIA_TRI_HD", nullable = false, precision = 22, scale = 0)
	public double getGiaTriHd() {
		return this.giaTriHd;
	}

	public void setGiaTriHd(double giaTriHd) {
		this.giaTriHd = giaTriHd;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hopDong")
	public Set<ChiTietHopDong> getChiTietHopDongs() {
		return this.chiTietHopDongs;
	}

	public void setChiTietHopDongs(Set<ChiTietHopDong> chiTietHopDongs) {
		this.chiTietHopDongs = chiTietHopDongs;
	}

}
