package dev.rapid.domain;
// Generated Jan 24, 2016 10:48:55 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * KhachHang generated by hbm2java
 */
@Entity
@Table(name = "khach_hang", catalog = "thamdinhgia_db")
public class KhachHang implements java.io.Serializable {

	private Integer idKh;
	private String tenKh;
	private String diaChi;
	private String sdt;
	private String fax;
	private String daiDien;
	private Set<HopDong> hopDongs = new HashSet<HopDong>(0);
	private String maSoThue;

	public KhachHang() {
	}

	public KhachHang(String tenKh, String diaChi, String sdt) {
		this.tenKh = tenKh;
		this.diaChi = diaChi;
		this.sdt = sdt;
	}

	public KhachHang(String tenKh, String diaChi, String sdt, String fax, String daiDien, Set<HopDong> hopDongs) {
		this.tenKh = tenKh;
		this.diaChi = diaChi;
		this.sdt = sdt;
		this.fax = fax;
		this.daiDien = daiDien;
		this.hopDongs = hopDongs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID_KH", unique = true, nullable = false)
	public Integer getIdKh() {
		return this.idKh;
	}

	public void setIdKh(Integer idKh) {
		this.idKh = idKh;
	}

	@Column(name = "TEN_KH", nullable = false, length = 100)
	public String getTenKh() {
		return this.tenKh;
	}

	public void setTenKh(String tenKh) {
		this.tenKh = tenKh;
	}

	@Column(name = "DIA_CHI", nullable = false, length = 100)
	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	@Column(name = "SDT", nullable = false, length = 20)
	public String getSdt() {
		return this.sdt;
	}

	public void setSdt(String sdt) {
		this.sdt = sdt;
	}

	@Column(name = "FAX", length = 20)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "DAI_DIEN", length = 100)
	public String getDaiDien() {
		return this.daiDien;
	}

	public void setDaiDien(String daiDien) {
		this.daiDien = daiDien;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "khachHang")
	public Set<HopDong> getHopDongs() {
		return this.hopDongs;
	}

	public void setHopDongs(Set<HopDong> hopDongs) {
		this.hopDongs = hopDongs;
	}

	@Column(name = "MA_SO_THUE", length = 15)
	public String getMaSoThue() {
		return this.maSoThue;
	}

	public void setMaSoThue(String maSoThue) {
		this.maSoThue = maSoThue;
	}

}
