package dev.rapid.domain;
// Generated Jan 24, 2016 10:48:55 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MayMocThietBi generated by hbm2java
 */
@Entity
@Table(name = "may_moc_thiet_bi", catalog = "thamdinhgia_db")
public class MayMocThietBi implements java.io.Serializable {

	private Integer idMmtb;
	private String loaiMay;
	private String model;
	private String nuocSanXuat;
	private Short namSanXuat;
	private String congSuat;
	private String trongLuong;
	private Double nguyenGia;
	private String moTaHienTrang;
	private Set<TaiSan> taiSans = new HashSet<TaiSan>(0);

	public MayMocThietBi() {
	}

	public MayMocThietBi(String loaiMay, String model, String nuocSanXuat, Short namSanXuat, String congSuat,
			String trongLuong, Double nguyenGia, String moTaHienTrang, Set<TaiSan> taiSans) {
		this.loaiMay = loaiMay;
		this.model = model;
		this.nuocSanXuat = nuocSanXuat;
		this.namSanXuat = namSanXuat;
		this.congSuat = congSuat;
		this.trongLuong = trongLuong;
		this.nguyenGia = nguyenGia;
		this.moTaHienTrang = moTaHienTrang;
		this.taiSans = taiSans;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_MMTB", unique = true, nullable = false)
	public Integer getIdMmtb() {
		return this.idMmtb;
	}

	public void setIdMmtb(Integer idMmtb) {
		this.idMmtb = idMmtb;
	}

	@Column(name = "LOAI_MAY", length = 100)
	public String getLoaiMay() {
		return this.loaiMay;
	}

	public void setLoaiMay(String loaiMay) {
		this.loaiMay = loaiMay;
	}

	@Column(name = "MODEL", length = 100)
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Column(name = "NUOC_SAN_XUAT", length = 100)
	public String getNuocSanXuat() {
		return this.nuocSanXuat;
	}

	public void setNuocSanXuat(String nuocSanXuat) {
		this.nuocSanXuat = nuocSanXuat;
	}

	@Column(name = "NAM_SAN_XUAT")
	public Short getNamSanXuat() {
		return this.namSanXuat;
	}

	public void setNamSanXuat(Short namSanXuat) {
		this.namSanXuat = namSanXuat;
	}

	@Column(name = "CONG_SUAT", length = 45)
	public String getCongSuat() {
		return this.congSuat;
	}

	public void setCongSuat(String congSuat) {
		this.congSuat = congSuat;
	}

	@Column(name = "TRONG_LUONG", length = 100)
	public String getTrongLuong() {
		return this.trongLuong;
	}

	public void setTrongLuong(String trongLuong) {
		this.trongLuong = trongLuong;
	}

	@Column(name = "NGUYEN_GIA", precision = 22, scale = 0)
	public Double getNguyenGia() {
		return this.nguyenGia;
	}

	public void setNguyenGia(Double nguyenGia) {
		this.nguyenGia = nguyenGia;
	}

	@Column(name = "MO_TA_HIEN_TRANG", length = 16777215)
	public String getMoTaHienTrang() {
		return this.moTaHienTrang;
	}

	public void setMoTaHienTrang(String moTaHienTrang) {
		this.moTaHienTrang = moTaHienTrang;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mayMocThietBi")
	public Set<TaiSan> getTaiSans() {
		return this.taiSans;
	}

	public void setTaiSans(Set<TaiSan> taiSans) {
		this.taiSans = taiSans;
	}

}
